### ISSUE TITLE
podman SELinux labels: spc_t vs unconfined_t

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1316]
[I vaguely recall asking about this some months ago and being told Not A Problem; but I can't find any supporting evidence. Filing just for the record. Please close with suitable explanation if necessary.]

```
# {docker,podman} run --rm --security-opt label=disable fedora cat /proc/self/attr/current |column -t -c14 -s: 
docker: system_u      system_r      spc_t         s0
podman: unconfined_u  unconfined_r  unconfined_t  s0

# {docker,podman} run --rm --privileged --userns=host fedora cat /proc/self/attr/current 
(same)
```
In particular, `unconfined_t` triggers a failure in one of the autotest-suite subtests.

podman-0.8.3-1.git9d09a4d.fc28 but this has been unchanged for months.

**Comment by rhatdan** [comment]
This is a know difference, and is somewhat difficult to fix without hard coding spc_t into podman.
What is going on here is docker runs as container_runtime_t.  When you disable SELinux via either --priviliged, --security-opt label:disabled or removing --selinux-enabled from docker then docker does not do the setting of the SELinux labels.
So we end up with container_runtime_t starting a process on container_share_t or container_file_t.

We have a transition rule in policy for this that says container_runtime_t @ container_file_t -> spc_t.

Now when a user runs podman, it is usually running as unconfined_t.  When we disable SELinux in podman, then we end up with unconfined_t  @container_file_t -> unconfined_t.  I could write a transition rule for this, but we usually don't like to transition from unconfined_t to some other domain.

**Comment by edsantiago** [comment]
And, presumably, there are good reasons for not running podman as `container_runtime_t`?

**Comment by rhatdan** [comment]
We could attempt a transition from unconfined_t @container_runtime_exec_t -> container_runtime_t for running podman. 

matchpathcon /usr/bin/podman
/usr/bin/podman	system_u:object_r:container_runtime_exec_t:s0

BTW This is what happens when systemd runs podman, it runs it as container_runtime_t.

And that might be the right thing to do.  But it does make me a little nervous.  We can make the change in Rawhide and see how it goes. 

The disk is redirection of content via bash.  You can get into some weird AVC's like contianer_runtime_t trying to write content to var_log_t, by executing commands like the following.

podman run foobar > /var/log/foobar.log

**Comment by rhatdan** [comment]
Yup.
