### ISSUE TITLE
Searching for images is slow

### ISSUE THREAD

**Issue by larskarlitski** [containers/libpod#2345]
/kind feature

@garrett investigated performance for searching images: https://github.com/cockpit-project/cockpit-podman/issues/55.

cockpit-podman would benefit from
* `SearchImages()` running searches in parallel
* `SearchImages()` returning results as soon as they're available
* `SearchImages()` to be able to filter by registry

podman version 1.0.0

**Comment by rhatdan** [comment]
@vrothberg Since you are our parallel speed guy could you look into this.
Would be helpful for podman search as well.
Perhaps we could do this for podman pull as well. 
Fire off threads for every registry rather then waiting for each to fail.  Problem with this would be if two had images of that name, we would not want to pull both.

**Comment by vrothberg** [comment]
Thanks for opening this issue, @larskarlitski!

@rhatdan, sounds good :) I'll look into it!

**Comment by vrothberg** [comment]
I opened https://github.com/containers/libpod/pull/2360. On my notebook, a `podman search ruby` drops from roughly 11 seconds to 2 seconds while providing identical output.
