### ISSUE TITLE
language: tag is not well-formed

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2494]
/kind bug

**Description**
Warning about a not-wellformed tag when parsing language.

**Steps to reproduce the issue:**
`podman --log-level debug run -it --rm --read-only busybox sh`

**Describe the results you received:**
`WARN[0000] failed to parse language "en_US.UTF-8": language: tag is not well-formed`

**Describe the results you expected:**
No warning :)

**Additional information you deem important (e.g. issue happens only occasionally):**
```
# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Output of `podman version`:**
```
podman version 1.2.0-dev
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 91373151335a84c5b78dbe46362cb678807d7509
  go version: go1.11.5
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 8de2ffc9e0809e98a72b93e35b74b8e5d4b0c29c'
  Distribution:
    distribution: debian
    version: "9"
  MemFree: 32108892160
  MemTotal: 38205562880
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: f79e211b1d5763d25fb8debda70a764ca86a0f23
      spec: 1.0.1-dev
  SwapFree: 8586784768
  SwapTotal: 8586784768
  arch: amd64
  cpus: 8
  hostname: pgsql
  kernel: 4.19.0-0.bpo.2-amd64
  os: linux
  rootless: false
  uptime: 26h 48m 2.64s (Approximately 1.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox 6 on Windows 10, running Debian 9 (stable)

**Comment by rhatdan** [comment]
@mtrmac Any idea what would cause this?

grep -r "tag is not well-formed" .
./vendor/golang.org/x/text/internal/language/parse.go:var ErrSyntax = errors.New("language: tag is not well-formed")

**Comment by mheon** [comment]
I think I know this one - it's trying to look up the system language so we
can determine what alphabetical sorting scheme to use for certain things
(hooks for one). This failure is basically harmless as such (we tried to
look up the system language and failed, so we'll just default to English).
I might be forgetting some details here, but I'm confident this isn't a bug.

If you really want it fixed, we look up language via a standard environment
variable, and so setting it correctly with remove the warning

**Comment by rhatdan** [comment]
I think it is better to ignore, since it breaks nothing.

**Comment by mtrmac** [comment]
> I think I know this one - it's trying to look up the system language so we can determine what alphabetical sorting scheme to use for certain things (hooks for one).

It’s hooks only, AFAICS, introduced in https://github.com/containers/libpod/pull/686 .

Why does it make sense for hook ordering to be locale-specific? When the default paths to hooks are system-wide like `/usr/share/containers/oci/hooks.d` and `/etc/containers/oci/hooks.d`, why is it at all desirable for different users on the same system using different locales to potentially process the same hook configuration in a different order?

IMHO the order should be consistent for all locales, and ideally invariant to upgrades of the locale database — which conceptually rules out _any_ human-language-focused rules, even if they were “hard-code to English collation order as defined by $dictionary and implemented in ICU”, because that can also change.

Especially if the practical recommendation is to order hooks by starting the file names with ASCII digits, there’s really no downside to just sorting the values by `[]byte` values of the UTF-8 representation (which is, BTW, equivalent to sorting by Unicode code point values).

> This failure is basically harmless as such (we tried to look up the system language and failed, so we'll just default to English). I might be forgetting some details here, but I'm confident this isn't a bug.

Looking at
```go
package main 
  
import (
        "golang.org/x/text/language"
        "fmt"
)

func main() {
        v, err := language.Parse("en_US.UTF-8") // "en_US"
        fmt.Printf("%v %v\n", v, err)
}
```
this code has _never_ succeeded ofr the UTF-8 locales in almost exclusive use; AFAICS the encoding is not a valid part of the “BCP 47” language tag.

**Comment by mtrmac** [comment]
> there’s really no downside to just sorting the values by []byte values of the UTF-8 representation 

Sadly, the current implementation is case-insensitive and explicitly documents such behavior even for ASCII, so at least `strings.ToLower` (which relies on an Unicode database) will continue to be necessary: see https://github.com/containers/libpod/pull/2501 .
