### ISSUE TITLE
[howto] pull PRs

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2678]
Since the Wiki isn't activated, I'm just dropping this howto in here... maybe you know a better place?
Sometimes it's possible to pull PRs to test them.

If you just want to pull a specific PR use this:
1. Set the variable _PR_ to the PR you want to pull `PR=1234`
2. Run `git fetch origin pull/$PR/head:pr/$PR`
3. Check out the PR: `git checkout pr/$PR`

If you want to run to integrate it into your normal workflow, use this:
1. Run `git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"`
2. Fetch all pull requests: `git fetch origin`
3. Check out the PR you want to build: `git checkout pr/1234`
You might add `--global` to step 1.

**Comment by rhatdan** [comment]
We could add this to the troublshooting.md page or to the install.md page.
@TomSweeneyRedHat WDYT?

**Comment by TomSweeneyRedHat** [comment]
Let me mull it over.  It's good info to have, but it's more git related rather than Podman related.  I don't think it should go into the troubleshooting, maybe the install or some kind of "How To Contribute" guide that doesn't yet exist.

**Comment by vrothberg** [comment]
I have the following script in my `~/bin/checkoutpr`:

```bash
#!/bin/bash -e

# fetch and checkout a github pull request
# Usage: checkoutpr $remote $PR-ID (e.g., checkoutpr upstream 007)

git fetch -f -u $1 pull/$2/head:pull-request-$2
git checkout pull-request-$2
```

If I want to locally test a PR, I just do a `checkoutpr upstream $PR_ID` with `upstream` being the git-remote pointing to github.com/containers/libpod.

**Comment by tobwen** [comment]
@vrothberg For portability:

```
#!/usr/bin/env bash
# fetch and checkout a github pull request
# Usage: checkoutpr $remote $PR-ID (e.g., checkoutpr upstream 007)
git fetch -f -u $1 pull/$2/head:pull-request-$2 && git checkout pull-request-$2
```

or wrap it into a function:
```
checkoutpr() { git fetch -f -u $1 pull/$2/head:pull-request-$2 && git checkout pull-request-$2 }
```

**Comment by rhatdan** [comment]
@tobwen is this still an issue?

**Comment by tobwen** [comment]
@rhatdan Never has been an issue. Would be nice to have a wiki :-)

**Comment by TomSweeneyRedHat** [comment]
I'm going to reopen this so the thought doesn't get lost, at least until we get something to contributors.md or some such.

**Comment by tobwen** [comment]
@TomSweeneyRedHat Wiiikkkiii :)

**Comment by rhatdan** [comment]
@rhatdan If you want to create the first page for the Wiki,we can turn it on.

**Comment by TomSweeneyRedHat** [comment]
I somehow sent the below the other day to @vrothberg directly rather than to this issue:

"I'm not against Wiki's in general, in fact at my prior stop we lived on Wiki's and it was kind of a culture shock when I came to Red Hat and they weren't to be found.  I don't know about GitHub's variant, haven't played with that.

I think this should go into the contrib.md files, but also having it on a wiki would be fine by me."

Since then I've set up a GitHub wiki for both Podman and Buildah.  Contributors to the respective projects should be able to write to it if they wish, all others will have read access.  I checked with GitHub directly and they unfortunately don't have the ability to set up a "Watch List" for a page or pages at this time like other wiki's have.  They've added that as a potential add at some point, but no commit to doing so.
