### ISSUE TITLE
Map container user to a "real" user

### ISSUE THREAD

**Issue by chpio** [containers/libpod#2790]
/kind feature

Hello,

i would like to map a container user to a "real" user. It would make the development process a lot easier. Im mounting local code directory into a container, then edit the code on the native side. It would be really nice, if the container user would be mapped to the native user. This would allow normal access on both sides, the container and the native side.

i have tried to join the irc channel, but i or the matrix.org-irc-bridge is banned on the #podman channel.

**Comment by vrothberg** [comment]
Hi @chpio,

thanks for opening the issue.

> i would like to map a container user to a "real" user. It would make the development process a lot easier. Im mounting local code directory into a container, then edit the code on the native side. It would be really nice, if the container user would be mapped to the native user. This would allow normal access on both sides, the container and the native side.

This should work already. If you are running on an selinux-enabled system you need to add the `Z` option to the volume/mount, e.g. 
```
$ podman run -v `pwd`:/test:Z alpine touch /test/foo
```

> i have tried to join the irc channel, but i or the matrix.org-irc-bridge is banned on the #podman channel.

I am using Matrix as well. The #podman channel requires users to be registered on Freenode. Can you check if your user is registered an retry?

**Comment by chpio** [comment]
I don't know if this is helping me, right now the `root` user is mapped to the executing user on the host, but i want also map another container user (in my case `www-data`/uid:33) to also my host user. I guess that's not possible?

**Comment by vrothberg** [comment]
I am sure @rhatdan or @giuseppe know some tricks?

**Comment by rhatdan** [comment]
You want to run a rootless container that treats your UID as your UID inside of the container.
Have you tried out toolbox?  It is a wrapper around podman that I think does what you want.

Rootless Podman defaults to mapping your UID to root inside of the container. But toolbox modifies podman's default behaviour to do mount the first UID of the /etc/subuid range to root inside of the container and then maps your UID into the container. 

Lets look at the default case of podman for a user test with UID=1000.
and /etc/subuild 
test:100000:65536

Podman sets up this mapping
         0       1000          1
         1     100000      65536

Toolbox tells podman to setup a different mapping

         0        100000       1000
         1000  1000           1
         1001  101001       64536

Hand edited, so I might have gotten this wrong.

podman run --security-opt label=disabled -v /home/test:/home/test --uidmap 0:100000:1000 --uidmap 1000:1000:1 --uidmap 1001:101001:64536 --workdir=${PWD} fedora sh

**Comment by giuseppe** [comment]
fedora-toolbox is doing what @rhatdan suggested.  Please reopen if this is still an issue

**Comment by merusso** [comment]
I don't think the --uidmap example that @rhatdan posted is accurate for rootless containers. There's some surprising behavior described in #6123 where you need to use `0` for the host UID instead of your real UID.

If you want to map a host UID to a container UID directly, you can use `--userns=keep-id`, but if you need to map the current host UID to a different container UID, you can use something like this: `--user $container_uid --uidmap $container_uid:0:1 --uidmap=0:1:1`.

(using Podman v3.0.1)

**Comment by userxfce** [comment]
Docker solves this elegantly:

$cat /etc/subuid
dockremap:500000:1
dockremap:1:65535
is all that it takes.

Why the strange complaint from podman that the ranges in /etc/subuid include the current user ID? It should be none of podman's concern.

Same problem is raised here: https://github.com/containers/podman/issues/5751#issue-595918773

**Comment by giuseppe** [comment]
> $cat /etc/subuid
> dockremap:500000:1
> dockremap:1:65535

Looks like you would like a way to define `--userns=keep-id` by default?

I don't think depending on a non-default configuration in `/etc/subuid` is better.   By default, only the additional IDs are added to `/etc/subuid` and `/etc/subgid` so doing what you are showing above requires root privileges.

Moving this complexity to the `podman unshare` stage will make things more difficult to handle from Podman, e.g. how would `--userns=nomap` work in this case or `--userns=keep-id`?

**Comment by userxfce** [comment]
I appreciate it, but:

$podman --version
podman version 3.4.4

"Error: cannot specify custom mappings with --userns=keep-id"

Podman on my system is old, it does not have that userns option implemented, but *why do not uidmap and gidmap options suffice*?

Until a future update of podman installation, the point is why the mapping of the current user ID to a container ID is so tricky, or why the current user ID is so inflexible.

Podman even goes so far that it complains about the ranges in /etc/subuid, which is a faulty design because other programs might actually rely on a specific /etc/subuid that podman does not like.

Podman could throw a warning or so, but refusing to run because of a /etc/subuid range is not on its taste is bad choice.

**Comment by userxfce** [comment]
"doing what you are showing above requires root privileges."

The *configuration* of docker requires root privileges (so does installing it in the first place), but *running containers* does not.

That is what actually my /etc/subuid file implements, the user mapping so that the root user of the container (and only that user) is not mapped on the root user of the host (but all the others do - this can be changed if I want finer grain).

The scenario is exactly where I would like that some operations are transparent (w.r.t. user ID) i they are performed from inside of the container or from the host, and I want to be able to configure that.

By the way, please improve the documentation on how one would use the toolbox to change the mapping as in this comment: https://github.com/containers/podman/issues/2790#issuecomment-479042318
