### ISSUE TITLE
Podman rmi output differs from Docker

### ISSUE THREAD

**Issue by mheon** [containers/libpod#2878]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When removing images, Docker is much more explicit as to what is going on than Podman.

Podman only prints a bare ID. Docker prints `Deleted: sha256:$ID` for all image SHAs, and then extra `Untagged:` lines for any names that are untagged.

**Steps to reproduce the issue:**

1. ```docker rmi `docker images -q` ```

2.`podman rmi -a`

**Describe the results you received:**

Podman does not match Docker's output

**Describe the results you expected:**

Podman prints the additional information that Docker does

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Current master built on F29

**Comment by mheon** [comment]
Noticed this while cooking up a fix for #2877

**Comment by baude** [comment]
@mheon i think we are OK with what we have.  do you still want this changed?

**Comment by mheon** [comment]
Still no `Untagged` and `Deleted` notices - we're definitely still different than Docker, and showing a lot less information on what's going on.

**Comment by baude** [comment]
Ok, lets hash this out.  I don't believe we need to provide more information as the output we are providing is exactly accurate.  I personally think the docker output for rmi is too verbose.  But for the sake of argument, we do differ in our output.  I attribute this to differences in our image management.  Looking at where we differ, I think it boils down to three basic areas:

1. We do prepend "Deleted" to the image ID being deleted.  That said, the command is "remove image", so if you run a command called remove image, it seems to me we are doing the right thing.

2. For removing images, Docker always does an untag and remove and reports it as a Untagged and Deleted.  If the case is that our image has only one repotag name, we do not report a tag because no tag actually occurs.

3. For removing images in podman, if an image has multiple images and the user requests to rmi one those repotag names, we respond that we untagged the image.

My vote is that we are doing enough here and because our image library differs from them, we are justified in doing as such.  Unless you are feeling strongly about this, I would like to close this issue and have a user report at some point why we need to make this kind of change?

**Comment by mheon** [comment]
The Docker 'Untagged: ...' syntax does make it clear that image IDs are not the only things being removed - names are also becoming inaccessible.

Example:
```
mcs@bellerophon code/libpod (fix_memory_leak) » sudo docker pull busybox                    
Using default tag: latest
Trying to pull repository docker.io/library/busybox ... 
sha256:9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70: Pulling from docker.io/library/busybox
ee153a04d683: Pull complete 
Digest: sha256:9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70
Status: Downloaded newer image for docker.io/busybox:latest
mcs@bellerophon code/libpod (fix_memory_leak) » sudo docker images --no-trunc | grep busybox
docker.io/busybox   latest              sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb   2 weeks ago         1.22 MB
mcs@bellerophon code/libpod (fix_memory_leak) » sudo docker rmi db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
Untagged: docker.io/busybox:latest
Untagged: docker.io/busybox@sha256:9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70
Deleted: sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
Deleted: sha256:0d315111b4847e8cd50514ca19657d1e8d827f4e128d172ce8b2f76a04f3faea
```

vs

```
mcs@bellerophon code/libpod (fix_memory_leak) » sudo podman pull busybox                                                                                                                                                                                                              1 ↵
Trying to pull docker.io/library/busybox...Getting image source signatures
Copying blob ee153a04d683 done
Copying config db8ee88ad7 done
Writing manifest to image destination
Storing signatures
db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
mcs@bellerophon code/libpod (fix_memory_leak) » sudo podman images --no-trunc | grep busybox
docker.io/library/busybox       latest            sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb   2 weeks ago     1.44 MB
mcs@bellerophon code/libpod (fix_memory_leak) » sudo podman rmi db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
```

Docker makes it clear that two layers (not just the top layer, as Podman reports) and two tags were removed. We don't do any of that right now.

**Comment by baude** [comment]
at the libpod level, we don't know about the later (layers).  and again, im not sure the users care about layer levels when they have asked to delete an image.  what do you think

**Comment by rhatdan** [comment]
I usually lean towards matching Docker functionality.  But I will leave this to you guys to figure out.

**Comment by baude** [comment]
this should now be doing what you wanted @mheon
