### ISSUE TITLE
Feedback on Podman

### ISSUE THREAD

**Issue by vsoch** [containers/libpod#3017]
Hey podman maintainers!

I wanted to give some feedback and have discussion about use cases for Podman, I've been testing it out a bit, and aside from a few blips it seems to be a re-creation of docker, minus the root daemon. It's a cool selling point that you could create an alias for podman to docker, but what's my incentive to do that? For the most part, the root daemon seems to be a non-starter for the HPC use case, but I don't think Podman is intended for HPC? In many enterprise / cloud technologies, despite this daemon, Docker is still a reasonable container to use.

What I want to bring up for discussion is why I should want to use Podman. As a user, why would I want to install it on my machine to build containers over Docker? If this point isn't nailed down, my best guess is that (the hope is that?) Podman will be waiting as a replacement in the rafters for if/when the Docker container ship (the company) finally sinks.

Let me know your thoughts! If there is a compelling use case, I'd like to test and then promote podman for that.

**Comment by rhatdan** [comment]
We have done this a little in the past
Here is my opinion of biggest pluses.

1. Rootless Containers - Gives users the ability to build/run/test containers without any privileges.  This is not something Docker can do well.  Setting up the Docker socket to be used by non privileged users is a huge security whole.
2. If all you want to do on a server is run a container at boot, why setup a big container daemon to run it.  Think of an appliance running 1 or two container apps, why would I need a daemon.
3. Open Running community willing to take PRs and look at other use cases, without forcing everything though a single way of doing things.
4.  Additional features like the management of Pods, Integration with Systemd, ability to transiton easily from a traditional container world to Kubernetes.

**Comment by vsoch** [comment]
Thanks @rhatdan, it interestingly sounds like Podman would be a good fit for HPC (although I don't think that's it's direct intention!) I don't admin any of our clusters so I don't have power to install and test it out, but I'll see if I can figure something out because I'd really like to. It would be cool to have more "docker like" containers in user space, as Singularity is read only.

**Comment by rhatdan** [comment]
Yes HPC is a great use case for Rootless Podman, and we have heard from a lot of people and customers who are looking at it.  Singularity is even looking to have their images move to OCI.

**Comment by vrothberg** [comment]
An additional point that might seem minor at first glance but can be a game changer for larger deployments spanning over multiple uses cases is that Podman plays well with its sibling projects [CRI-O](https://github.com/cri-o/cri-o), [Buildah](https://github.com/containers/buildah), and [Skopeo](https://github.com/containers/skopeo). I think this turns all projects into a *composable Swiss army knife*. Composable because users can independently chose which tools to use for their use-case up to the point of having the entire army knife (using all of them) for all kinds of use-cases when working with containers.

All projects share the same building blocks, namely the [containers/image](https://github.com/containers/image) and [containers/storage](https://github.com/containers/storage) libraries. This allows a certain degree of inter-operability and compatibility such as for sharing the image storage, the containers storage (if desired) and for sharing the various supported image transports (e.g., registry, storage, oci, tar, docker-daemon etc.). In the analogy of the Swiss army knife, all parts play well together but users have the choice which they want or need to use.

**Comment by rhatdan** [comment]
Excellent point, and from a security point of view the different tools have different security requirements, allowing us to taylor higher and lower levels of defaults depending on the use case.

**Comment by vsoch** [comment]
Thanks @vrothberg and @rhatdan - you are correct that Singularity became OCI compliant for the 3.0* family.  I definitely see the points, and I'm mostly having trouble putting together a user story for my particular user group (academic scientists), and convincing myself too. I'll keep trying, thanks for your thoughtful responses.
