### ISSUE TITLE
Update podman in RHEL extras

### ISSUE THREAD

**Issue by h-vetinari** [containers/libpod#3044]
The last available podman version in RHEL (7.6) extras is 0.12.1.2, which is already almost [1400 commits behind master](https://github.com/containers/libpod/releases?after=v1.0.0), and not usable (to me) in several ways, especially related to multi-stage builds (cf. containers/buildah#632, containers/buildah#1456, containers/buildah#1463).

This issue is to (publically?) track a new release to that channel, since I depend on a soonish release in that regard...

Xref: A month ago @lsm5 [mentioned](https://github.com/containers/libpod/issues/2250#issuecomment-477589575) that
> > @h-vetinari: [...] when can I install something newer than podman ~0.11.1~ 0.12.1.2 on a RHEL 7.6 machine?

> @lsm5: [...] Something newer than that will take a few weeks more I guess.

**Comment by baude** [comment]
would this be more appropriate as a bugzilla?

**Comment by h-vetinari** [comment]
@baude 
Is this something for me to file, or more for RH-people?

**Comment by lsm5** [comment]
@h-vetinari RHEL updates are being worked on, but that takes a while to get through the release process, and sometimes issues keep us from pushing those. Remind me again please, are you a RHEL or CentOS user? If you use CentOS, newer packages can be fetched from the SIG repos.

**Comment by h-vetinari** [comment]
> @lsm5: Remind me again please, are you a RHEL or CentOS user? 

RHEL user, and restricted to the official channels for support reasons.

**Comment by fatherlinux** [comment]
@h-vetinari thanks for reaching out on this. RHEL 7 dot release operate on a 6+ (sometimes up to 11 months) lifecycle. To solve this, we have released podman in Extras which means, we "can update more often than that, but we try to be careful doing so. Those 1200 commits can also include new bugs, so it's always a balancing act of when to make a commitment to role versions in RHEL.

That said, what features specifically are blocking your needs? I ask, because we have a plan to update the release when we release RHEL 7.7 (targeted for August) and the plan is to support Rootless in that release (hence it taking a bit longer than we would have liked). 

Are you tied to RHEL 7.X or might you be able to try out RHEL 8 Beta?

One final question, do you have  TAM? Or, could you open a ticket with Red Hat because the upstream really tracks engineering changes to the actual code of Podman (aka new code), while the internal Red Hat support system helps track package updates (aka packaging).

P.S. I am the product manger for the Container Subsystem in RHEL, so I very much want to get this to you. We "like" when you use the official channels in RHEl because it helps us better support you, and provide better QE, integration support (other products, partners, etc). Feel free to reach out to me any time for packaging needs like this.

Best Regards
Scott M

**Comment by h-vetinari** [comment]
@fatherlinux 
Thanks a lot for the response!

I'm happy to go through whatever channels are the most appropriate, but I have the limitation that I'm not actually responsible for the RHEL infrastructure at the company, I'm just building stuff that needs podman, and am particularly hitting issues relating to multistage builds (cf. containers/buildah#632, containers/buildah#1456, containers/buildah#1463), and firewalls/packaging (#2887).

As such, I unfortunately have no choice to upgrade to 8.0 Beta (once 8.0 comes out, I'm guessing it will take 2-3 month before I can actually get it on a machine, whereas updating from extras was quite painless so far). I also don't have a TAM, but I can *maybe* find out who that might be for the company.

Is there a way to file something in the official channels that does not require a TAM or active subscription? If so, I'm happy to do it. If not, it'll probably take me a while to go through all the channels with local IT.

**Comment by michielhemme** [comment]
Well RHEL 8 just released. Unfortanaly the package used is 1.02-dev or something like that. Everything will work except rootless portmapping.

**Comment by h-vetinari** [comment]
> @michielhemme: Everything will work except rootless portmapping.

That's unfortunately not true for me. The bugs I referenced only got fixed with 1.2/1.3.

**Comment by michielhemme** [comment]
@fatherlinux , Currently RHEL8 installs podman version 1.0.0.2. This version is lacking Port binding support for rootless users. Could I ask you if rootless port binding support(Podman 1.12+) will be released soon within RHEL 8? If so when?

**Comment by rhatdan** [comment]
@michielhemme There is no podman 1.12, the next release is podman 1.3.  Definitely will be in RHEL8.1 hopefully sooner.

**Comment by fatherlinux** [comment]
@michielhemme @h-vetinari thank you both for you interest in podman, we are super excited about it. We are working on updating the version of podman to 1.3+ in RHEL 8.1 (November-ish) and RHEL 7.7 (August-ish). We are just coming out of two huge launches (RHEL 8.0 and OpenShift 4.0) so trying diligently to get these updated.

**Comment by h-vetinari** [comment]
@fatherlinux 
No chance of having a 1.3.1 "canary" in 7.6 extras before August-September...?

**Comment by fatherlinux** [comment]
@h-vetinari so, I love to under promise and over deliver ;-) We were able to get Podman 1.3.1 into 7.6.5 which is impending. While I can't commit to date, we are looking green for release any day now :-) Look for the drop very soon.

**Comment by h-vetinari** [comment]
> @fatherlinux: [...] We were able to get Podman 1.3.1 into 7.6.5 which is impending. [...]

Wow, that is excellent news - thank you very much for your efforts!
