### ISSUE TITLE
podman-remote - support login/logout

### ISSUE THREAD

**Issue by deanpeterson** [containers/libpod#4039]
I installed podman on mac using homebrew but there is no login command. It is completely unrecognized and it doesn't even show in --help as an option.

**Comment by baude** [comment]
the decision to not support login is intentional because performing a login on the mac itself probably does the user no good.  this is because when pulling, for example, the pull is actually being done on a linux backend where you have pointed the podman client.

@rhatdan we still comfortable with this decision?

**Comment by rhatdan** [comment]
No I think we need to have some support for login, since the user will not be able to use the container.  Can't we just do the login on the server, and keep the keys there?

**Comment by baude** [comment]
i dont see why not ... just need to plan for it and add the remote endpoints for it

**Comment by rhatdan** [comment]
@QiWang19 ^^

**Comment by vrothberg** [comment]
Changed the title as it generally affects the remote client.

@baude @rhatdan @QiWang19, we should discuss how to implement it. Storing the credentials on the endpoint seems undesirable and ~insecure. Storing them on the client-side will require to update a considerable amount of APIs, since the credentials need to be passed. Hence, supporting the remote use-case could end up in some _very_ intrusive and breaking changes.

**Comment by philbert** [comment]
I want to get rid of the docker desktop for something more lightweight... but I immediately ran into this issue with a colleague (who runs podman on linux) and the two of us were totally confused and gave up after 15 minutes.

Now after reading the readme I am no less confused about how I might use buildah or podman and whether or not I can finally replace the awful docker desktop.

And by "awful" I mean this...
<img width="526" alt="image" src="https://user-images.githubusercontent.com/5618563/65538414-8a537080-df07-11e9-8fe0-005e7f9d8c4e.png">

**Comment by baude** [comment]
@philbert stick with us ... the only question at this point is how to do it safely/securely.

**Comment by edmacabebe** [comment]
Right. I'm trying to push to an image registry in ocp4.1 made possible by codeready in my laptop. According to docs, podman login -u kubeadmin -p $(oc whoami -t) <image-registry-url>:5000 should work, but since it's not available yet...what work around do I have? Back to using docker for now?

**Comment by rhatdan** [comment]
@baude Lets raise the priority of this, and get something in the next sprint.

**Comment by codrinbucur** [comment]
in my view, any cli commands should be uniform across operating systems. it doesn't make sense to not have "login" just on macos

**Comment by rhatdan** [comment]
This is being worked on.

**Comment by clutchbeyers** [comment]
Any updates to this? Impacting openshift 4.2 documentation on MACOSX using podman

**Comment by rhatdan** [comment]
Well most of the effort has been refocused on implementing the Docker API.  Should have more news after the holidays.

**Comment by rhatdan** [comment]
The APIV2 code has been merged into the upstream master, but still aways from podman remote work.

**Comment by rhatdan** [comment]
@baude @jwhonce Has the APIs for login/logout been implemented in the new API yet

**Comment by rcondondev** [comment]
I have podman version 1.6.1-dev installed on mac, "podman login" still not available. any alternative?

**Comment by rhatdan** [comment]
Not yet, that is part of the podman V2 effort.

**Comment by rhatdan** [comment]
It does now.
