### ISSUE TITLE
write-only volume

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#4546]
/kind feature

**Description**
For privacy reasons, I'd love to have a write-only volume. It should be possible to write content from a container to a volume, but not read it back.

Of course, there's place for discussions: What should happen, if a file is already existing? Either overwrite or append it...

Maybe it should better get a feature of https://github.com/containers/fuse-overlayfs than _podman_?

**Alternatives**
https://www.arthy.org/wocfs/

**Comment by rhatdan** [comment]
I believe you would need a special file system, perhaps a fuse file system for this.  This is not something that Podman could provide.  If you have a WRITEONLY file system and mounted it into the container then this would work.

@giuseppe Any comment, on using Fuse for this?

**Comment by tobwen** [comment]
I thought, it would be possible to limit the capabilities of a mount to "write only". Sure, fuse would be a better place.

**Comment by mheon** [comment]
I think this should be possible (but only as root) if a write-only filesystem exists, via volumes with mount options (which can mount a filesystem as a volume). These are presently root-only because we don't have permissions to mount filesystems without root, though theoretically we could un-restrict this to allow FUSE mounts as rootless?

**Comment by rhatdan** [comment]
Correct, rootless podman can and does mount fuse file system.  (well in the PR for overlay mounts)
