### ISSUE TITLE
lists.podman.io is unberable slow (impossible to use)

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4661]
The currently advertised mailing list seems not to be really functional. I spent more than an hour trying to register, confirm and post a message. Apparently is also moderated.

While there are only a couple of messages posted it seems that the mailing list website is almost impossible to use. I spent >30 min to manage to create and login only.

The average time to load a page is 10s-20s, which indicates some serious infra issue. 

https://lists.podman.io/archives/profile/ --- time to load 19s 

Can someone take a look at this?

I cannot refrain from wondering why we do not re-use another public mailing list service instead of spinning up a new one. To me it would make more sense to avoid extra maintenance needed and use something else.

The current state of https://lists.podman.io may explain why it has so few users.

PS. It would be good to add an `infra` label what we could use to mark infrastructure related issue, like github, services, irc.

**Comment by TomSweeneyRedHat** [comment]
@ssbarnea Thanks for the heads up.  This is the first I've heard of issue like this with the list.  When I've used it, it's always been very speedy, I don't think I've waited more than a second or two to transition from one page to another.  I'll go see if there's something going on there.

**Comment by karl-tpio** [comment]
FWIW, it's speedy for me.

> The average time to load a page is 10s-20s, which indicates some serious infra issue.

Can you check your browsers dev tool, specifically the network tab? What request(s) are consuming the most time and in what phase of the request does the time go (DNS, handshake/tls negotiation, content transfer... etc) ?

**Comment by TomSweeneyRedHat** [comment]
@ssbarnea I played around with the web interface yesterday from work and from my home PC's and I think the longest transition I had was close to 2 seconds, most were well under a second.  

I just wanted to verify that the slowness you mentioned was that rather than the slowness to become a member when you register.  We'd a really bad spam attack in early November and required people to get OK'd by an admin before they became registered.  Unfortunately the server didn't sent mail out to the admins so we'd not realized a number of signups had come in, we were several weeks behind in getting those taken care of.

**Comment by vrothberg** [comment]
The issue seems to be resolved now; just tested. Please re-open if you are still experiencing performance issue.
