### ISSUE TITLE
unable to rebase apiv2 branch and master

### ISSUE THREAD

**Issue by baude** [containers/libpod#4771]
I seem to be unable to properly rebase master on top of the apiv2 branch.  Here is what I do.

1. start with latest upstream/apiv2
2. git rebase --master and resolve all conflicts
3. push a pr against upstream/apiv2
4. results in unable to merge do to file conflicts (several examples in pull requests now)

am i doing this wrong?

@mheon any advice?

**Comment by mheon** [comment]
Looking...

**Comment by mheon** [comment]
Examples? I can't see it in your latest APIv2 PR

**Comment by vrothberg** [comment]
I think that rebasing will get tougher and tougher. The APIv2 branch has many (and many dirty commits). It might be worth squashing them at some time and keeping the `Signed-off` fields; this will make rebasing easier.

Another approach could be merging (`git merge upstream/master`) and creating just one commit that brings the two branches together. But that would keep the dirty commits which could be annoying when bisecting issues. I'd prefer squashing into one big commit.

**Comment by mheon** [comment]
Do we want to discuss a permanent merge into master, but keeping things segregated from the rest of Podman from now (not built by default from the makefile, etc)? The more things we stuff into the branch, the more painful the final review+merge is going to be.

**Comment by baude** [comment]
@mheon an example would be https://github.com/containers/libpod/pull/4733

yeah, i think by EOW next week, we might be ready to do so.  but for now, just need to get master updated in apiv2 so that work can continue.

**Comment by mheon** [comment]
I think it's natural we get conflicts in this case. We can't really rebase a branch via PR - PRs are merges, so we're trying to meld two incompatible commit trees. You'd need to do a force-push against the apiv2 branch to update it. You can rebase a branch that is being PR'd against the latest version of that same branch, but a rebase doesn't translate well to PR form - I think it'd act like it was bringing every commit in master not present in the branch into the PR, and apply those on top of existing commits (instead of moving the commits of the branch on top of the new base from master).

**Comment by baude** [comment]
@mheon so should i just rebase again and force push?

**Comment by mheon** [comment]
I think you'd need to force push to upstream/apiv2 instead of trying to PR against it.

**Comment by baude** [comment]
after a rebase with master yes?

**Comment by rhatdan** [comment]
Yes, I agree, it is time to merge this into Master.
