### ISSUE TITLE
Confirmation prompt for 'container prune' breaks non-interactive use

### ISSUE THREAD

**Issue by StefanBruens** [containers/libpod#4844]
/kind bug

**Description**

With podman 1.7.0, it is no longer possible to prune containers from a script.

The prompt can be avoided by adding `--force`, but this will also prune running containers.

Please add a `--yes`/`-y` flag to allow confirmation from a script.

The prompt was added here:
https://github.com/containers/libpod/commit/0602ce4dc04ec1b78724019e03066b8562877b73

**Steps to reproduce the issue:**

`podman container prune && echo "OK"` 

**Describe the results you received:**

```
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N]
```

**Describe the results you expected:**

`OK`

**Output of `podman version`:**

1.7.0

**Comment by mheon** [comment]
Wait, container prune --force prunes running? That sounds like a bug.

**Comment by StefanBruens** [comment]
https://github.com/containers/libpod/blob/master/cmd/podman/containers_prune.go#L43

**Comment by mheon** [comment]
It's possible the description there may be inaccurate. `prune --force` should only remove stopped containers, but with no prompt. I need to verify if this is actually the case.

**Comment by baude** [comment]
@mheon @StefanBruens this just tripped me up as well while i was working on the apiv2 stuff so i had to look at the code as well.  it turns out the description is incorrect.  the force should only be used to skip the interactive bit.  however, it IS passed onto the container removal call.  that said, we are safe here because prune uses container filters to select which containers to prune.  therefore the force is basically a no-op.  i'll see about a quick pr to tidy this up.
