### ISSUE TITLE
--cgroup-manager option is missing from mac version

### ISSUE THREAD

**Issue by medyagh** [containers/libpod#5101]
while trying to add podman driver for minikube https://github.com/kubernetes/minikube/pull/6515
I noticed on mac
```
podman --cgroup-manager
Error: unknown flag: --cgroup-manager
```
podman version:

```
Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64

Service:
Version:            1.7.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.10
Git Commit:         ce4bf33ccc80819f199bdbb6526b9adee1ad41b0-dirty
Built:              Sat Jan 18 02:01:17 2020
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
This is intentional; global configuration flags like `--cgroup-manager` are server-side only, and should be configured on the Podman service there.

**Comment by medyagh** [comment]
ok makes sense !

**Comment by afbjorklund** [comment]
I think some of the confusion here comes because `podman-remote` is called podman on the Mac...

For boot2podman, the regular ISO uses "cgroupfs" whereas the fedora ISO uses "systemd".
There isn't really a way to change it before boto, except for rebuilding the images I suppose.

Will bring it over to minikube, since kubeadm wants systemctl - I think it is better off using Fedora.
