### ISSUE TITLE
Commit for CRI-O containers

### ISSUE THREAD

**Issue by mheon** [containers/libpod#526]
/kind feature

We'd like to be able to generate images from CRI-O container using `podman commit`. This would allow builds to be executed within a CRI-O container, and the results to be committed as a new image.

This discussion branched from https://github.com/projectatomic/buildah/issues/375 where it was decided the responsibility would be better suited to `podman`.

This will require completing `libpod` integration into CRI-O - blockers to that are listed at #500 

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
> /kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@rhatdan @smarterclayton This should supplant https://github.com/projectatomic/buildah/issues/375 if we agree that `podman commit` is the way forward.

**Comment by smarterclayton** [comment]
I probably won't be able to look at this until friday or monday but I definitely want to discuss.

The model we have been discussing (not decided yet, of course) where a worker daemonset offers a docker socket to other pods that then invokes buildah (openshift/image-build-daemon prototype) would want to do the following:

1. from the originating pod, identify cgroups and other pod security restrictions
2. as root in the daemonset pod, use the host's storage (if available) or a side storage
3. launch a container under the pod's cgroup to be the host for each RUN command
4. if the originating pod dies, ensure the container gets cleaned up and any host resources released

The part I'm most worried about is 3 and 4 - ensuring we don't have a half solution.  Having the kubelet own the container because it's part of the pod definition is great - but we also have the problem that we need to do the git clone inside the pod, *then* based on the Dockerfile from the clone decide what containers to launch.  If kube is running the pod container it's too late to add new containers (unless debug containers lands, but that's messy too).  We could just use a generic image and then do a mount into it that we control, but i haven't had a chance to think about the rough edges.

At this point my worry is that we could *do* anything, but we need to be really crisp about requirements, so before we go too far in any direction we need to decide what the right solution is based on those requirements.  A rough list right now in roughly priority order is:

1. we can bring existing openshift use cases over without modification (multi-stage builds, image source, etc)
2. we can keep the security model simple (limit what the calling pod can do)
3. we can swap out Docker without users noticing, and we can keep the openshift build control plane layer oblivious to what container runtime is in use 
4. we can make the running pods be cleaned up correctly, preferably by having the kubelet own them
5. we can reuse host images safely and in the future look at other perf optimizations.

**Comment by mheon** [comment]
So the model is to have a pod on each node providing build services via a socket that will be exposed to other pods, but to share resource limitations of the pod that requested the build, if I read this correctly? Hm.

Are we trying to keep the daemonset pod providing the build service unprivileged? This is a whole lot harder architecturally if we are.

**Comment by smarterclayton** [comment]
No, we aren't trying to keep it unprivileged.  The identifying and tracking
callers part is done.  What's not clear yet is whether the end result of
that is supportable.  The build requirements from openshift require a way
to set up containers at runtime for multi-stage builds.  We might actually
have that via Kube at some point, but short term it's not an option.

**Comment by mheon** [comment]
Alright, if we're privileged, we can share pods and containers with the host CRI-O instance. That should allow us to solve the resource constraints problem (we can directly insert a container into the pod that is doing the build). Podman was originally billed as a debug tool for CRI-O, so that much should be easy. Cleanup might not be so easy, though. The containers will be managed with the pod from a CRI-O perspective, but Openshift didn't directly request them, so Openshift doesn't really know about them.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan's comment sounds an awful lot like:  https://github.com/projectatomic/buildah/issues/531 @ipbabble.

**Comment by mheon** [comment]
For cleanup, we support containers that remove themselves after running. Once the cleanup callback work I'm doing is ready, that should be a native part of libpod, and fairly resilient. We can run `buildah` in such a container inside the pod requesting the build, and the container should remove itself and clean up associated resources. Potential problem: the container would also be managed with the pod, so Kube requesting a `stop` on the pod would stop the build container before the build was complete, effectively cancelling it (it'd still remove itself, so no resource leaks, at least).

**Comment by rhatdan** [comment]
Where do we stand on this one?

**Comment by mheon** [comment]
@rhatdan I think rootless buildah is the majority of this work. Once we have Podman and CRI-O on libpod, we can work out the details of running in an existing pod from there.

**Comment by vrothberg** [comment]
@mheon Out of curiosity: How's the CRI-O port on libpod going?

**Comment by rhatdan** [comment]
@vrothberg @baude opened the first PR for this to add images support.  Right now we are planning on adding support with build tags so we can easily switch back and forth and run tests for performance without jeapordizing CRI-O.  
But we have decided our main focus right now is to get podman to 1.0 by end of summer.

**Comment by rhatdan** [comment]
https://github.com/kubernetes-incubator/cri-o/pull/1669

**Comment by vrothberg** [comment]
Once CRI-O is ported on libpod, wouldn't `podman-commit` work like any other command on CRI-O containers (given the right namespace is used)? I wonder if we can close this issue as it seems to be an implicit part of the libpod port.

**Comment by rhatdan** [comment]
Yes I think we can close this.

**Comment by rhatdan** [comment]
BTW, I think podman commit should not have much effect for containers running in CRI-O, since I believe that containers running in CRI-O should be read/only by default.  Meaning their is nothing to commit.
