### ISSUE TITLE
Different error messages when getting 503 when pulling images

### ISSUE THREAD

**Issue by HarryMichal** [containers/libpod#5288]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling images with `podman pull` from registry.fedoraproject.org I sometimes get a 503 HTTP status. That is most likely a problem of the registry itself. Problem is that there are 2 slightly different messages for the 503 HTTP status. I can see that they are coming from different parts of the codebase but still, the error type is the same.

I'm not sure if this behavior is intended or if it truly is a bug.

**Steps to reproduce the issue:**

Call the following command several times in a row. Either you'll get the `manifest unknown` error or one of the reported ones.

1. `podman pull registry.fedoraproject.org/123`

The pulled image can be any nonexistent image.

**Describe the results you received:**

Two different error messages :

First
```
Trying to pull registry.fedoraproject.org/123...
  received unexpected HTTP status: 503 Service Temporarily Unavailable
Error: error pulling image "registry.fedoraproject.org/123": unable to pull registry.fedoraproject.org/123: unable to pull image: Error initializing source docker://registry.fedoraproject.org/123:latest: Error reading manifest latest in registry.fedoraproject.org/123: received unexpected HTTP status: 503 Service Temporarily Unavailable
```

Second
```
Trying to pull registry.fedoraproject.org/123...
  invalid status code from registry 503 (Service Unavailable)
Error: error pulling image "registry.fedoraproject.org/123": unable to pull registry.fedoraproject.org/123: unable to pull image: Error initializing source docker://registry.fedoraproject.org/123:latest: error pinging docker registry registry.fedoraproject.org: invalid status code from registry 503 (Service Unavailable)
```

**Describe the results you expected:**

One kind of error message. It doesn't matter which one.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.14rc1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.14rc1
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.11-0.6.dev.git86aa80b.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.11-dev, commit: b6ad06ed817c8b9d68bb7b92f32b7fb6d08bbb8f'
  Distribution:
    distribution: fedora
    version: "32"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1032843264
  MemTotal: 16655794176
  OCIRuntime:
    name: crun
    package: crun-0.12.2.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.2.1
      commit: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8413769728
  SwapTotal: 8413769728
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: harry-work
  kernel: 5.6.0-0.rc2.git0.1.fc32.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-6.0.dev.gita8414d1.fc32.x86_64
    Version: |-
      slirp4netns version 0.4.3+dev
      commit: a8414d1d1629f6f7a93b60b55e183a93d10d9a1c
  uptime: 4h 40m 43.65s (Approximately 0.17 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /home/omichal/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.6-2.0.dev.gitce61c7e.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  GraphRoot: /var/home/omichal/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/omichal/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-4.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running Fedora Silverblue 32. BaseCommit in `rpm-ostree` is: `2b5dc2909a83537cae81b061d5230e32efe5f94aeea3cc57c5dc96a839f998f4`

**Comment by mheon** [comment]
These look like errors from different parts in the pull process. The first is from initially verifying the registry is reachable; the second is from attempting to pull the image. I don't know if we want to drop the extra information here, as it could be valuable for debugging.

**Comment by mheon** [comment]
Speaking more generally, while I definitely do understand the request here, it's difficult to give consistent errors on registry operations in general. While most of the implementation of a registry is standardized, there's enough differences between implementations for it to be impossible for us to know for certain what went wrong on getting an error back.

In cases like this, for non-debug logs, we could look into shortening/cleaning up error messages, but I'm not sure how much we can do. Really depends on how the errors we're getting back from c/image are formatted.

**Comment by jwhonce** [comment]
@mtrmac Please comment.

**Comment by HarryMichal** [comment]
I would propose just to unify the wording of the last part of the errors. Either choose `received unexpected HTTP status: 503 Service Temporarily Unavailable` or `invalid status code from registry 503 (Service Unavailable)`. At least from my point of you that wouldn't disrupt debugging too much.

If the unification was done then the first two lines would look the same (and that kinda makes sense to me because in both cases an unexpected 503 was received) but the third line that actually shows the whole trace would explain what and where exactly happened.

**Comment by mtrmac** [comment]
Overall this feels like an attempt to script around a failing server by grepping an error message; it feels way too easy to recommend “just” fixing the server in the first place instead of trying to check for errors that should not be happening, or maybe retrying on _all_ kinds of errors except those specifically recognized[1] instead retrying only on one.

---

In general, error texts returned by c/image are _never_ an API, and should not be relied on by any software.

(The cases when c/image returns a well-typed error that _is_ an API are fairly rare, admittedly. We do add such APIs if handling them in code is necessary, e.g. to report “invalid credentials”. But, see above about fixing the server instead — it’s hard to see why a 503 should be an API.)

---

> error pinging docker registry registry.fedoraproject.org: invalid status code from registry 503 (Service Unavailable)

This is a check whether the server even _is_ a registry, and to discover some of its properties. A response like that may well indicate a user error (pointing at a server that is not a registry).

> Error reading manifest latest in registry.fedoraproject.org/123: received unexpected HTTP status: 503 Service Temporarily Unavailable

At this point the server is known to be a registry, and is expected to report user-readable errors using a specific HTTP response payload, along with a restricted set of HTTP statutes. Returning 503 is plainly invalid behavior from the server, not an user error the user can fix locally.

The expectations of the response are plainly different in the two cases, so it’s not too attractive for the client to _commit_ to behaving in the same way. It would be not logically valid to use the (third-party) error parsing code for the “known to be a registry” case in the “might not be a registry” case. It would, sure, be possible to write tests that simulate the two kinds of failures, and test that they produce the same string, and manually keep the two in sync, but this really feels like a failure situation that should be fixed instead of specifically detected and somehow worked around (Shall we next fix 502? Invalid Gzip encoding? Why one and not the other?), so I’m reluctant to to take on that burden.

---

[1] Detecting specific error kinds should really be done through a Go API, though; the texts are not an API.

**Comment by rhatdan** [comment]
I am going to close this as the registry needs to be fixed.
