### ISSUE TITLE
Detach key interferes with shell history navigation in interactive container

### ISSUE THREAD

**Issue by jcrd** [containers/libpod#5979]
/kind bug

**Description**

With the default detach key combo `ctrl-p,ctrl-q`, shell history navigation (tested in bash and zsh) using `ctrl-p` to access the previous command will not display this command. However, adding additional characters to the command will cause it to be displayed, and using `ctrl-p` a second time will display the 2nd to last command.

**Steps to reproduce the issue:**

1. `podman run -it <image> bash`

2. Enter a command: `echo`

3. Enter a second command: `test`

4. Press `ctrl-p`. Nothing will be displayed.

5. Type a character, e.g. `c`: `testc` will be displayed.
**or** Press `ctrl-p` again: `echo` will be displayed.

**Describe the results you received:**

Command history is not displayed properly.

**Describe the results you expected:**

Previous command should be displayed in shell.

**Output of `podman version`:**

```
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.13.9
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.9
  podmanVersion: 1.9.0
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 4152e6044da92e0c5f246e5adf14c85f41443759'
  cpus: 12
  distribution:
    distribution: fedora
    version: "31"
  eventLogger: journald
  hostname: escapade
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.5.17-200.fc31.x86_64
  memFree: 13829607424
  memTotal: 16794615808
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc31.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.1.0
  swapFree: 6872363008
  swapTotal: 6872363008
  uptime: 17m 43.53s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/james/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.8-1.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.8
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  graphRoot: /home/james/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 27
  runRoot: /run/user/1000/containers
  volumePath: /home/james/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.0-1.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This occurs on a physical machine.

**Comment by mheon** [comment]
Sorry for the delay here, the team's been very busy with Podman v2.0 over the last month.

This is an artifact of our detach key logic, which actually pauses sending any keystrokes until it confirms it is not the detach keys (IE, until a key has been pressed following the C-p, the code assumes it could be a C-p C-q, so sends nothing). I can't think of a way of altering that behaviour without making us send a C-p to the container when we're actually detaching, which could break things.

My initial suggesting would be to make `C-p C-p` send a single control-p into the container; making it two keys makes it unambiguous that it's not `C-p C-q` but still allows sending single a single press of the first key in the detach sequence. This has precedent from `tmux` (and I believe screen, but it's been years since I used it) where `C-b C-b` sends a single press of `C-b`.

Potential complexity: we allow reassigning detach keys, so someone could theoretically set `C-p C-p` as the actual detach keys. In that case, it may be reasonable to just disable the "send single keypress" behaviour (and tell people not to use a repeated key if they do want to be able to use it in the container).

**Comment by jcrd** [comment]
Thanks for the thorough explanation.

My workaround is to use a detach key combo with an unconflicting first keystroke:
`detach_keys = "ctrl-q,ctrl-q"`

**Comment by rhatdan** [comment]
Sadly Docker picked a bad default.  Since the ^p key is used by default in bash for previous message.
You can use containers.conf to change the default for all containers.
```
# cat >> /etc/containers/containers.conf < _eof
[engine]
detach_keys="ctrl-q,ctrl-q"
_eof
```

**Comment by rhatdan** [comment]
Added a PR with documentation https://github.com/containers/libpod/pull/6455
