### ISSUE TITLE
podman pod create POD

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#6778]
Why no `podman pod create POD` for parity with `podman pod rm POD`?

Or is it waiting for https://github.com/containers/podman-compose to specify a file?

**Comment by baude** [comment]
the parity is `podman pod create` and `podman pod rm`

**Comment by abitrolly** [comment]
Oops. Fixed.

**Comment by baude** [comment]
are you talking about assigning a name to the pod?

**Comment by abitrolly** [comment]
Yes.

**Comment by baude** [comment]
do you object to the use of `--name`?

**Comment by abitrolly** [comment]
For scripts it doesn't matter, but for command line I forget about it.

**Comment by abitrolly** [comment]
@rhatdan so why no `podman pod create NAME`?

**Comment by rhatdan** [comment]
podman container create uses --name


podman volume create
podman network create

Work the way you want, so I guess we could/should do Pods the same way.  Interested in opening a PR for this?

**Comment by abitrolly** [comment]
@rhatdan seems easy. Takes time to setup dev env though. Are there plans for `podman pod create` to use templates like kubernetes?

**Comment by rhatdan** [comment]
We use `podman play kube` for that.  It reads a kubernetes yaml file and creates the pod.

**Comment by abitrolly** [comment]
Wow. I didn't even know that.

**Comment by abitrolly** [comment]
Are there any simple formats planned for defining pods? I've got a feeling that Kubernetes artillery is too heavy for startups, and `docker-compose` model is too limited to a single node to be followed 1 to 1.

**Comment by rhatdan** [comment]
Podman goal is not to be an orchestrator, only to work with orchestrators, If community wants to add podman play compose, we would listen.  There is also a podman-compose project.

Podman 2.0 has implemented the APIV2 which should be able to support Docker-compose and other docker-py based libraries.

When it comes to orchestrators we plan to push people towards Kubernetes, because we believe this is the future.
